# HTTP Configuration
http.host=0.0.0.0
http.port=8081

# Elasticsearch Configuration
elasticsearch.host=localhost
elasticsearch.port=9200
elasticsearch.url=http://${elasticsearch.host}:${elasticsearch.port}

# Default Index Configuration
elasticsearch.default.index=my-index

# Logging Configuration
logging.level=INFO
